const bulls = {
    player: {
        name: "Demar DeRozan",
        position: "SF", 
        ppg: 22.2,
        apg: 5.3,
        rpg: 3.7,
        age: 34,
        salary: 27,
    }, 
    player: {
        name: "Zach Lavine",
        position: "SG"
        ppg: 20.7,
        apg: 3.4,
        rpg: 4.9,
        age: 28,
        salary: 43,
    }, 
    player: {
        name: "Coby White",
        position: "PG",
        ppg: 17.9,
        apg: 4.9,
        rpg: 4.4,
        age: 23,
        salary: 7.4,
    }, 
    player: {
        name: "Nicola Vucevic",
        position: "C",
        ppg: 16.5,
        apg: 3.4,
        rpg: 10.3,
        age: 33,
        salary: 28,
    }, 
    player: {
        name: "Patrick Williams",
        position: "PF",
        ppg: 10.0,
        apg: 1.5,
        rpg: 4.0,
        age: 22,
        salary: 7.75,
    }, 
    player: {
        name: "Alex Caruso",
        position: "SG",
        ppg: 10.0,
        apg: 2.5,
        rpg: 3.5,
        age: 29,
        salary: 9.46,
    }, 
    player: {
        name: "Ayo Dosunmu",
        position: "SG",
        ppg: 8.1,
        apg: 1.9,
        rpg: 2.5,
        age: 23,
        salary: 1.56,
    }, 
    player: {
        name: "Andre Drummond",
        position: "C",
        ppg: 7.3,
        apg: 0.5,
        rpg: 8.6,
        age: 30,
        salary: 3.28,
    }, 
    player: {
        name: "Torrey Craig",
        position: "SF",
        ppg: 6.1,
        apg: 1.0,
        rpg: 4.8,
        age: 33,
        salary: 5.37,
    }, 
    player: {
        name: "Jevon Carter",
        position: "PG",
        ppg: 5.3,
        apg: 1.3,
        rpg: 0.8,
        age: 28,
        salary: 6.5,
    }, 
    player: {
        name: "Dalen Terry",
        position: "F",
        ppg: 2.4,
        apg: 1.3,
        rpg: 2.0,
        age: 21,
        salary: 3.35,
    }, 
    player: {
        name: "Terry Taylor",
        position: "F",
        ppg: 1.8,
        apg: 0.2,
        rpg: 1.2,
        age: 24,
        salary: 2.10,
    },
    player: {
        name: "Julian Phillips",
        position: "F",
        ppg: 0.9,
        apg: 0.3,
        rpg: 0.5,
        age: 20,
        salary: 2.02,
    },
    player: {
        name: "Onuralp Bitim",
        position: "SF",
        ppg: 0.0,
        apg: 0.0,
        rpg: 0.0,
        age: 24,
        salary: 0.56,
    },
};

const lakers = {
    player: {
        name: "LeBron James",
        position: "SF", 
        ppg: 25.2,
        apg: 7.4,
        rpg: 7.3,
        age: 39,
        salary: 47.61,
    }, 
    player: {
        name: "Anthony Davis",
        position: "PF", 
        ppg: 25.3,
        apg: 3.4,
        rpg: 12.3,
        age: 30,
        salary: 40.60,
    }, 
    player: {
        name: "DeAngelo Russel",
        position: "PG", 
        ppg: 14.8,
        apg: 6.1,
        rpg: 2.9,
        age: 27,
        salary: 17.31,
    }, 
    player: {
        name: "Rui Hachimura",
        position: "PF", 
        ppg: 11.6,
        apg: 1.1,
        rpg: 3.6,
        age: ,
        salary: 17.31,
    }, 
    player: {
        name: "Austin Reaves",
        position: "SG", 
        ppg: 15.4,
        apg: 5.2,
        rpg: 4.5,
        age: 25,
        salary: 12.01,
    }, 
    player: {
        name: "Gabe Vincent",
        position: "PG", 
        ppg: 5.4,
        apg: 3.0,
        rpg: 1.0,
        age: 27,
        salary: 10.50,
    }, 
    player: {
        name: "Taurean Prince",
        position: "PF", 
        ppg: 9.8,
        apg: 1.9,
        rpg: 2.9,
        age: 29,
        salary: 7.45,
    }, 
    player: {
        name: "Jarred Vanderbilt",
        position: "PF", 
        ppg: 2.5,
        apg: 0.7,
        rpg: 4.0,
        age: 24,
        salary: 4.70,
    }, 
    player: {
        name: "Jalen Hood-Schifino",
        position: "G", 
        ppg: 2.3,
        apg: 0.6,
        rpg: 1.0,
        age: 20,
        salary: 3.69,
    }, 
    player: {
        name: "Christian Wood",
        position: "PF", 
        ppg: 7.1,
        apg: 1.0,
        rpg: 5.5,
        age: 28,
        salary: 2.71,
    }, 
    player: {
        name: "Cam Reddish",
        position: "SF", 
        ppg: 6.7,
        apg: 1.5,
        rpg: 2.6,
        age: 24,
        salary: 2.17,
    }, 
    player: {
        name: "Jaxson Hayes",
        position: "C", 
        ppg: 2.9,
        apg: 0.3,
        rpg: 1.8,
        age: 23,
        salary: 2.17,
    }, 
    player: {
        name: "Max Christie",
        position: "G", 
        ppg: 4.9,
        apg: 1.0,
        rpg: 2.9,
        age: 20,
        salary: 1.72,
    }, 
    player: {
        name: "Maxwell Lewis",
        position: "F", 
        ppg: 0.3,
        apg: 0.3,
        rpg: 0.3,
        age: 21,
        salary: 1.20,
    }, 
};
